# Generated by Django 4.2.3 on 2023-07-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('need_transport', models.BooleanField(default=False)),
                ('want_breakfast', models.BooleanField(default=True)),
                ('booking_date', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
