# Generated by Django 4.2.3 on 2023-07-19 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        ('customer', '0004_alter_customer_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
    ]
