# Generated by Django 4.2.3 on 2023-07-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='room_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='room_start',
            field=models.DateField(null=True),
        ),
    ]
