# Generated by Django 4.2.3 on 2023-07-20 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_is_booked'),
        ('customer', '0006_customer_room_end_customer_room_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
    ]
